name = "PlasmoPlots"
uuid = "a21664a3-f668-4e98-8a13-7892286ec16a"
authors = ["Jordan Jalving <jhjalving@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Colors = ">=0.12"
GeometryBasics = ">=0.4"
Graphs = "1"
NetworkLayout = ">=0.4"
Plasmo = "0.6"
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
